import openai

openai.api_key = OPENAI_API_KEY

response = openai.Completion.create(
  model="text-davinci-003",
  prompt="Write a poem about programming",
  temperature=0.7,
  max_tokens=256,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0
)

poem = response['choices'][0]['text']

print(poem)

header = '''
# openai-random-poem
 A poem generated by OpenAI


### poem
'''

file = open('README.md', 'w')
file.write(header + poem)
file.close()
